name: Pipeline for aploading artifacts

on: push

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Generate list using Markdown
     run: |
      "This is the lead in sentence for the list" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append

   - name: checkout the code
     uses: actions/checkout@v4
   - run: python hello.py
  Upload:
    needs: [ build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v2
        with:
           name: hello
           path: .
           
         
    
